on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          npm ci
          npm run build --if-present

    # Uncomment once tests are added.
    # - name: Test
    #   run: npm test
